apiVersion: v1
kind: Service
metadata:
  name: go-loadtest-api
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: go-loadtest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-loadtest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-loadtest-api
  template:
    metadata:
      labels:
        app: go-loadtest-api
    spec:
      containers:
      - name: go-loadtest-api
        image: jmb12686/go-loadtest-api:latest
        resources:
          limits:
            cpu: "0.25"
        ports:
        - containerPort: 8000